/**
 * 単語帳データ。
 *
 * 単語を追加するときは、対象の deck の words に
 * { term: "見出し語", reading: "読み/発音(任意)", meaning: "意味" }
 * を足すだけでよい。ID は term から自動生成されるため、
 * 途中に単語を挿入しても既存の学習進捗はずれない。
 */
(function (global) {
  'use strict';

  var DECKS = [
    {
      id: 'en',
      name: '英語',
      emoji: '🇬🇧',
      words: [
        { term: 'abandon', reading: 'əˈbændən', meaning: '見捨てる、放棄する' },
        { term: 'ability', reading: 'əˈbɪləti', meaning: '能力' },
        { term: 'accept', reading: 'əkˈsept', meaning: '受け入れる' },
        { term: 'accurate', reading: 'ˈækjərət', meaning: '正確な' },
        { term: 'achieve', reading: 'əˈtʃiːv', meaning: '達成する' },
        { term: 'admit', reading: 'ədˈmɪt', meaning: '認める' },
        { term: 'advantage', reading: 'ədˈvæntɪdʒ', meaning: '利点、強み' },
        { term: 'afford', reading: 'əˈfɔːrd', meaning: '〜する余裕がある' },
        { term: 'allow', reading: 'əˈlaʊ', meaning: '許可する' },
        { term: 'ancient', reading: 'ˈeɪnʃənt', meaning: '古代の' },
        { term: 'anxious', reading: 'ˈæŋkʃəs', meaning: '不安な、切望して' },
        { term: 'appreciate', reading: 'əˈpriːʃieɪt', meaning: '感謝する、価値を認める' },
        { term: 'approach', reading: 'əˈproʊtʃ', meaning: '近づく、取り組み方' },
        { term: 'argue', reading: 'ˈɑːrɡjuː', meaning: '議論する、主張する' },
        { term: 'arrange', reading: 'əˈreɪndʒ', meaning: '手配する、並べる' },
        { term: 'attempt', reading: 'əˈtempt', meaning: '試みる、試み' },
        { term: 'available', reading: 'əˈveɪləbl', meaning: '利用できる、手が空いた' },
        { term: 'avoid', reading: 'əˈvɔɪd', meaning: '避ける' },
        { term: 'aware', reading: 'əˈwer', meaning: '気づいている' },
        { term: 'balance', reading: 'ˈbæləns', meaning: '均衡、残高' },
        { term: 'behavior', reading: 'bɪˈheɪvjər', meaning: '行動、ふるまい' },
        { term: 'benefit', reading: 'ˈbenɪfɪt', meaning: '利益、恩恵' },
        { term: 'borrow', reading: 'ˈbɑːroʊ', meaning: '借りる' },
        { term: 'brief', reading: 'briːf', meaning: '短い、簡潔な' },
        { term: 'capable', reading: 'ˈkeɪpəbl', meaning: '能力がある' },
        { term: 'cause', reading: 'kɔːz', meaning: '原因、引き起こす' },
        { term: 'challenge', reading: 'ˈtʃælɪndʒ', meaning: '課題、挑戦する' },
        { term: 'charge', reading: 'tʃɑːrdʒ', meaning: '請求する、充電する' },
        { term: 'claim', reading: 'kleɪm', meaning: '主張する、要求する' },
        { term: 'comfortable', reading: 'ˈkʌmftəbl', meaning: '快適な' },
        { term: 'compare', reading: 'kəmˈper', meaning: '比較する' },
        { term: 'complain', reading: 'kəmˈpleɪn', meaning: '不平を言う' },
        { term: 'concern', reading: 'kənˈsɜːrn', meaning: '心配、関係する' },
        { term: 'confident', reading: 'ˈkɑːnfɪdənt', meaning: '自信がある' },
        { term: 'consider', reading: 'kənˈsɪdər', meaning: '検討する、みなす' },
        { term: 'contain', reading: 'kənˈteɪn', meaning: '含む' },
        { term: 'continue', reading: 'kənˈtɪnjuː', meaning: '続ける' },
        { term: 'convenient', reading: 'kənˈviːniənt', meaning: '便利な、都合のよい' },
        { term: 'crowd', reading: 'kraʊd', meaning: '群衆' },
        { term: 'curious', reading: 'ˈkjʊriəs', meaning: '好奇心が強い' },
        { term: 'decide', reading: 'dɪˈsaɪd', meaning: '決める' },
        { term: 'decrease', reading: 'dɪˈkriːs', meaning: '減少する' },
        { term: 'deliver', reading: 'dɪˈlɪvər', meaning: '配達する、届ける' },
        { term: 'demand', reading: 'dɪˈmænd', meaning: '要求する、需要' },
        { term: 'depend', reading: 'dɪˈpend', meaning: '頼る、次第である' },
        { term: 'describe', reading: 'dɪˈskraɪb', meaning: '描写する、説明する' },
        { term: 'develop', reading: 'dɪˈveləp', meaning: '発展させる、開発する' },
        { term: 'difficult', reading: 'ˈdɪfɪkəlt', meaning: '難しい' },
        { term: 'discover', reading: 'dɪˈskʌvər', meaning: '発見する' },
        { term: 'divide', reading: 'dɪˈvaɪd', meaning: '分ける' },
        { term: 'doubt', reading: 'daʊt', meaning: '疑う、疑い' },
        { term: 'eager', reading: 'ˈiːɡər', meaning: '熱心な、切望して' },
        { term: 'effort', reading: 'ˈefərt', meaning: '努力' },
        { term: 'encourage', reading: 'ɪnˈkɜːrɪdʒ', meaning: '励ます、促す' },
        { term: 'environment', reading: 'ɪnˈvaɪrənmənt', meaning: '環境' },
        { term: 'escape', reading: 'ɪˈskeɪp', meaning: '逃げる' },
        { term: 'essential', reading: 'ɪˈsenʃl', meaning: '不可欠な' },
        { term: 'estimate', reading: 'ˈestɪmeɪt', meaning: '見積もる' },
        { term: 'evidence', reading: 'ˈevɪdəns', meaning: '証拠' },
        { term: 'familiar', reading: 'fəˈmɪliər', meaning: 'よく知っている、なじみの' }
      ]
    },
    {
      id: 'es',
      name: 'スペイン語',
      emoji: '🇪🇸',
      words: [
        { term: 'la casa', meaning: '家' },
        { term: 'el agua', meaning: '水' },
        { term: 'el trabajo', meaning: '仕事' },
        { term: 'la ciudad', meaning: '都市、町' },
        { term: 'el amigo', meaning: '友達' },
        { term: 'comer', meaning: '食べる' },
        { term: 'beber', meaning: '飲む' },
        { term: 'hablar', meaning: '話す' },
        { term: 'escribir', meaning: '書く' },
        { term: 'leer', meaning: '読む' },
        { term: 'vivir', meaning: '住む、生きる' },
        { term: 'el libro', meaning: '本' },
        { term: 'la comida', meaning: '食事、食べ物' },
        { term: 'la mañana', meaning: '朝、午前' },
        { term: 'la noche', meaning: '夜' },
        { term: 'el día', meaning: '日、昼' },
        { term: 'grande', meaning: '大きい' },
        { term: 'pequeño', meaning: '小さい' },
        { term: 'bonito', meaning: 'きれいな、かわいい' },
        { term: 'caro', meaning: '(値段が)高い' },
        { term: 'barato', meaning: '安い' },
        { term: 'rápido', meaning: '速い' },
        { term: 'despacio', meaning: 'ゆっくりと' },
        { term: 'siempre', meaning: 'いつも' },
        { term: 'nunca', meaning: '決して〜ない' },
        { term: 'ahora', meaning: '今' },
        { term: 'después', meaning: '後で' },
        { term: 'aprender', meaning: '学ぶ' },
        { term: 'enseñar', meaning: '教える' },
        { term: 'entender', meaning: '理解する' },
        { term: 'querer', meaning: '欲しい、〜したい' },
        { term: 'poder', meaning: '〜できる' },
        { term: 'saber', meaning: '(知識として)知っている' },
        { term: 'conocer', meaning: '(面識が)ある、知り合う' },
        { term: 'la calle', meaning: '通り' },
        { term: 'el coche', meaning: '車' },
        { term: 'el dinero', meaning: 'お金' },
        { term: 'la familia', meaning: '家族' },
        { term: 'feliz', meaning: '幸せな' },
        { term: 'cansado', meaning: '疲れた' }
      ]
    },
    {
      id: 'fr',
      name: 'フランス語',
      emoji: '🇫🇷',
      words: [
        { term: 'la maison', meaning: '家' },
        { term: "l'eau", reading: 'f.', meaning: '水' },
        { term: 'le travail', meaning: '仕事' },
        { term: 'la ville', meaning: '都市、町' },
        { term: "l'ami", reading: 'm.', meaning: '友達' },
        { term: 'manger', meaning: '食べる' },
        { term: 'boire', meaning: '飲む' },
        { term: 'parler', meaning: '話す' },
        { term: 'écrire', meaning: '書く' },
        { term: 'lire', meaning: '読む' },
        { term: 'habiter', meaning: '住む' },
        { term: 'le livre', meaning: '本' },
        { term: 'le repas', meaning: '食事' },
        { term: 'le matin', meaning: '朝' },
        { term: 'la nuit', meaning: '夜' },
        { term: 'le jour', meaning: '日、昼間' },
        { term: 'grand', meaning: '大きい' },
        { term: 'petit', meaning: '小さい' },
        { term: 'beau', meaning: '美しい' },
        { term: 'cher', meaning: '(値段が)高い、親愛な' },
        { term: 'vite', meaning: '速く' },
        { term: 'lentement', meaning: 'ゆっくりと' },
        { term: 'toujours', meaning: 'いつも' },
        { term: 'jamais', meaning: '決して〜ない' },
        { term: 'maintenant', meaning: '今' },
        { term: 'plus tard', meaning: '後で' },
        { term: 'apprendre', meaning: '学ぶ' },
        { term: 'enseigner', meaning: '教える' },
        { term: 'comprendre', meaning: '理解する' },
        { term: 'vouloir', meaning: '欲しい、〜したい' },
        { term: 'pouvoir', meaning: '〜できる' },
        { term: 'savoir', meaning: '(知識として)知っている' },
        { term: 'connaître', meaning: '(面識が)ある、知っている' },
        { term: 'la rue', meaning: '通り' },
        { term: 'la voiture', meaning: '車' },
        { term: "l'argent", reading: 'm.', meaning: 'お金' },
        { term: 'la famille', meaning: '家族' },
        { term: 'heureux', meaning: '幸せな' },
        { term: 'fatigué', meaning: '疲れた' },
        { term: 'le temps', meaning: '時間、天気' }
      ]
    },
    {
      id: 'de',
      name: 'ドイツ語',
      emoji: '🇩🇪',
      words: [
        { term: 'das Haus', meaning: '家' },
        { term: 'das Wasser', meaning: '水' },
        { term: 'die Arbeit', meaning: '仕事' },
        { term: 'die Stadt', meaning: '都市、町' },
        { term: 'der Freund', meaning: '友達' },
        { term: 'essen', meaning: '食べる' },
        { term: 'trinken', meaning: '飲む' },
        { term: 'sprechen', meaning: '話す' },
        { term: 'schreiben', meaning: '書く' },
        { term: 'lesen', meaning: '読む' },
        { term: 'wohnen', meaning: '住む' },
        { term: 'das Buch', meaning: '本' },
        { term: 'das Essen', meaning: '食事' },
        { term: 'der Morgen', meaning: '朝' },
        { term: 'die Nacht', meaning: '夜' },
        { term: 'der Tag', meaning: '日、昼' },
        { term: 'groß', meaning: '大きい' },
        { term: 'klein', meaning: '小さい' },
        { term: 'schön', meaning: '美しい' },
        { term: 'teuer', meaning: '(値段が)高い' },
        { term: 'billig', meaning: '安い' },
        { term: 'schnell', meaning: '速い' },
        { term: 'langsam', meaning: 'ゆっくりな' },
        { term: 'immer', meaning: 'いつも' },
        { term: 'nie', meaning: '決して〜ない' },
        { term: 'jetzt', meaning: '今' },
        { term: 'später', meaning: '後で' },
        { term: 'lernen', meaning: '学ぶ' },
        { term: 'lehren', meaning: '教える' },
        { term: 'verstehen', meaning: '理解する' },
        { term: 'wollen', meaning: '〜したい' },
        { term: 'können', meaning: '〜できる' },
        { term: 'wissen', meaning: '(知識として)知っている' },
        { term: 'kennen', meaning: '(面識が)ある、知っている' },
        { term: 'die Straße', meaning: '通り' },
        { term: 'das Auto', meaning: '車' },
        { term: 'das Geld', meaning: 'お金' },
        { term: 'die Familie', meaning: '家族' },
        { term: 'glücklich', meaning: '幸せな' },
        { term: 'müde', meaning: '疲れた' }
      ]
    },
    {
      id: 'ko',
      name: '韓国語',
      emoji: '🇰🇷',
      words: [
        { term: '집', reading: 'jip', meaning: '家' },
        { term: '물', reading: 'mul', meaning: '水' },
        { term: '일', reading: 'il', meaning: '仕事、こと' },
        { term: '도시', reading: 'dosi', meaning: '都市' },
        { term: '친구', reading: 'chingu', meaning: '友達' },
        { term: '먹다', reading: 'meokda', meaning: '食べる' },
        { term: '마시다', reading: 'masida', meaning: '飲む' },
        { term: '말하다', reading: 'malhada', meaning: '話す' },
        { term: '쓰다', reading: 'sseuda', meaning: '書く、使う' },
        { term: '읽다', reading: 'ikda', meaning: '読む' },
        { term: '살다', reading: 'salda', meaning: '住む、生きる' },
        { term: '책', reading: 'chaek', meaning: '本' },
        { term: '밥', reading: 'bap', meaning: 'ご飯、食事' },
        { term: '아침', reading: 'achim', meaning: '朝、朝食' },
        { term: '밤', reading: 'bam', meaning: '夜' },
        { term: '낮', reading: 'nat', meaning: '昼' },
        { term: '크다', reading: 'keuda', meaning: '大きい' },
        { term: '작다', reading: 'jakda', meaning: '小さい' },
        { term: '예쁘다', reading: 'yeppeuda', meaning: 'きれいだ' },
        { term: '비싸다', reading: 'bissada', meaning: '(値段が)高い' },
        { term: '싸다', reading: 'ssada', meaning: '安い' },
        { term: '빠르다', reading: 'ppareuda', meaning: '速い' },
        { term: '느리다', reading: 'neurida', meaning: '遅い' },
        { term: '항상', reading: 'hangsang', meaning: 'いつも' },
        { term: '절대', reading: 'jeoldae', meaning: '決して' },
        { term: '지금', reading: 'jigeum', meaning: '今' },
        { term: '나중에', reading: 'najunge', meaning: '後で' },
        { term: '배우다', reading: 'baeuda', meaning: '学ぶ' },
        { term: '가르치다', reading: 'gareuchida', meaning: '教える' },
        { term: '이해하다', reading: 'ihaehada', meaning: '理解する' },
        { term: '원하다', reading: 'wonhada', meaning: '望む、欲しい' },
        { term: '할 수 있다', reading: 'hal su itda', meaning: '〜できる' },
        { term: '알다', reading: 'alda', meaning: '知っている' },
        { term: '모르다', reading: 'moreuda', meaning: '知らない' },
        { term: '길', reading: 'gil', meaning: '道' },
        { term: '차', reading: 'cha', meaning: '車、お茶' },
        { term: '돈', reading: 'don', meaning: 'お金' },
        { term: '가족', reading: 'gajok', meaning: '家族' },
        { term: '행복하다', reading: 'haengbokhada', meaning: '幸せだ' },
        { term: '피곤하다', reading: 'pigonhada', meaning: '疲れている' }
      ]
    },
    {
      id: 'zh',
      name: '中国語',
      emoji: '🇨🇳',
      words: [
        { term: '家', reading: 'jiā', meaning: '家' },
        { term: '水', reading: 'shuǐ', meaning: '水' },
        { term: '工作', reading: 'gōngzuò', meaning: '仕事' },
        { term: '城市', reading: 'chéngshì', meaning: '都市' },
        { term: '朋友', reading: 'péngyou', meaning: '友達' },
        { term: '吃', reading: 'chī', meaning: '食べる' },
        { term: '喝', reading: 'hē', meaning: '飲む' },
        { term: '说', reading: 'shuō', meaning: '話す' },
        { term: '写', reading: 'xiě', meaning: '書く' },
        { term: '读', reading: 'dú', meaning: '読む' },
        { term: '住', reading: 'zhù', meaning: '住む' },
        { term: '书', reading: 'shū', meaning: '本' },
        { term: '饭', reading: 'fàn', meaning: 'ご飯' },
        { term: '早上', reading: 'zǎoshang', meaning: '朝' },
        { term: '晚上', reading: 'wǎnshang', meaning: '夜' },
        { term: '白天', reading: 'báitiān', meaning: '昼間' },
        { term: '大', reading: 'dà', meaning: '大きい' },
        { term: '小', reading: 'xiǎo', meaning: '小さい' },
        { term: '漂亮', reading: 'piàoliang', meaning: 'きれいな' },
        { term: '贵', reading: 'guì', meaning: '(値段が)高い' },
        { term: '便宜', reading: 'piányi', meaning: '安い' },
        { term: '快', reading: 'kuài', meaning: '速い' },
        { term: '慢', reading: 'màn', meaning: '遅い' },
        { term: '总是', reading: 'zǒngshì', meaning: 'いつも' },
        { term: '从不', reading: 'cóngbù', meaning: '決して〜ない' },
        { term: '现在', reading: 'xiànzài', meaning: '今' },
        { term: '以后', reading: 'yǐhòu', meaning: '後で' },
        { term: '学习', reading: 'xuéxí', meaning: '学ぶ' },
        { term: '教', reading: 'jiāo', meaning: '教える' },
        { term: '明白', reading: 'míngbai', meaning: '理解する' },
        { term: '想要', reading: 'xiǎngyào', meaning: '欲しい、〜したい' },
        { term: '能', reading: 'néng', meaning: '〜できる' },
        { term: '知道', reading: 'zhīdào', meaning: '知っている' },
        { term: '认识', reading: 'rènshi', meaning: '(面識が)ある、見知っている' },
        { term: '路', reading: 'lù', meaning: '道' },
        { term: '车', reading: 'chē', meaning: '車' },
        { term: '钱', reading: 'qián', meaning: 'お金' },
        { term: '家人', reading: 'jiārén', meaning: '家族' },
        { term: '幸福', reading: 'xìngfú', meaning: '幸せな' },
        { term: '累', reading: 'lèi', meaning: '疲れた' }
      ]
    }
  ];

  // term から安定した ID を作る（並び替えても進捗が壊れない）
  DECKS.forEach(function (deck) {
    deck.words.forEach(function (word) {
      word.id = deck.id + ':' + word.term;
      word.deckId = deck.id;
    });
  });

  function getDeck(deckId) {
    return DECKS.filter(function (deck) {
      return deck.id === deckId;
    })[0] || null;
  }

  var api = { DECKS: DECKS, getDeck: getDeck };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
  } else {
    global.Decks = api;
  }
})(typeof window !== 'undefined' ? window : globalThis);
